### ISSUE TITLE
UnboundLocalError: local variable 'accept' referenced before assignment

### ISSUE THREAD

**Issue by jackditto** [manwhoami/Bella#1]
I just want to say I love this project and what y'all are doing here. I followed all the instructions and built this program, and then I set it up to listen. However, when I connected to it from another Mac on my LAN, I got an error:

Traceback (most recent call last):
  File "./Control Center.py", line 606, in <module>
    main()
  File "./Control Center.py", line 203, in main
    if(accept):
UnboundLocalError: local variable 'accept' referenced before assignment

I looked at the code for Control Center.py and I believed that the the error is coming from the block on line 190. I changed the code to print out the error, and it was this:

[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)

I tried to see if there is any way to fix this, but I don't know enough about this to do anything. Hope this helps though :-)

**Comment by manwhoami** [comment]
Quite peculiar. I am looking into the issue. If you would like a temporary work around, you can disable the socket encryption.

It goes without saying that this is not recommended!!!

To do this, in `Bella.py`, replace `bellaConnection = ssl.wrap_socket(sock, ssl_version=ssl.PROTOCOL_TLSv1, cert_reqs=ssl.CERT_NONE)` with `bellaConnection = sock`

and in `Control Center.py`, replace line 190, the line that was causing you trouble `sock, accept = ssl.wrap_socket(binder, ssl_versio....` with `sock, accept = binder.accept()`

Again, disabling the socket encryption is not recommended. Any communications between the Control Center and Bella will be sent in the clear, susceptible to sniffing. 

Let me know of any further developments.

**Comment by manwhoami** [comment]
Hey, do you think you could post a stack traceback of the exception?
```
import traceback
traceback.print_exc()
```

**Comment by Skeyelab** [comment]
I too am getting this error.  My control center is installed on a VM on digital ocean and I can port scan it and see the port is open, but when I do, CC crashes with

```Traceback (most recent call last):
File "./Control Center.py", line 606, in 
main()
File "./Control Center.py", line 199, in main
if(accept):
UnboundLocalError: local variable 'accept' referenced before assignment```

**Comment by manwhoami** [comment]
Can I get more information about your setup? Should work [and as ive tested does work] fine on a Digital ocean instance. 

This error occurs when you get an IOError when generating certificates to encrypt the file, an IOError than is not 2 [no file or directory exists].

I have updated the Control Center to print and raise the exception that is causing this.

Please re-download the CC and let me know what happens, so we can address what is wrong with your setup.

**Comment by manwhoami** [comment]
Closing to inactivity, as well as update that should solve problem.
