### ISSUE TITLE
Labels and User Switching [Enhancement]

### ISSUE THREAD

**Issue by thehappydinoa** [manwhoami/Bella#11]
Hi, I really love what you are doing with Bella and I wanted to make a few suggestions. First, I think adding the ability to name clients would be amazing, right now I would have to change the client's hostname or memorize a bunch of host names. I tried doing this myself with no such luck, I hope you can do it. Second, I think it would be great if we could change users if we got the password for another account. Thanks! Also comment if you think this should be implemented.

**Comment by manwhoami** [comment]
Hey, thanks for the request. I added this feature. You will need to update your clients to this latest version. You can call this function through `set_client_name`.

Side-note: I am working on a function that will update client code in a clean fashion.

**Comment by thehappydinoa** [comment]
Thanks man!
