### ISSUE TITLE
D

### ISSUE THREAD

**Issue by thehappydinoa** [manwhoami/Bella#13]

**Comment by manwhoami** [comment]
Thank you for all the suggestions. I encourage as many as you have!

@ **changing folder name ... DONE**

@ **keylogger** . the ruby reference looks great. I will peek into that and see about integrating it with bella. I have been working with some c implementations, but they all require root access, which is less than ideal. this ruby one doesn't seem to, which is good.

@ **custom prompts** what exactly do you mean by this? Bella supports bash commands, so you can just run the AppleScript commands there are you normally would.

@ **webcam snaps** I have considered this using an imagesnap payload. Concerns - not at all stealthy, so I guess it can be use at your own risk. will implement soon.

@ **bulk commands** I have considered this extensively. It would require a *lot* of reworking of the Control Center [e.g., if we want to send a bulk command to phish passwords, we would have to thread a socket for each remote bella connection for it to all happen simultaneously]. 

Thanks for suggestions. Will get working on them. Keep them coming.

**Comment by thehappydinoa** [comment]
@manwhoami, thanks so much for considering all my suggestions, just a little update, when I was talking about the custom prompts I meant like the keychain and iTunes ones you made, I was just hoping to be able to do './BUILDER Payload.py' or something and link to an image give it some text and have it inject into an application, it is painstaking to do in base64
