### ISSUE TITLE
OH GOD?!?!??!

### ISSUE THREAD

**Issue by xSynthx** [manwhoami/Bella#15]
Well, now that I have completely removed the old Bella folder, and got cloned the new updated version, when I run Control Center, I get this when I do `control` + `c` after a client has connected
```
^C[*] Emptying socket. You have to wait for this task to end.
[1] S'\x1b[31m[-] \x1b[0mMalfunction:\n```\n\x1b[31mTraceback (most recent call last):\n  File "/Library/Containers/.bella/Bella", line 1760, in bella\n    data = recv_msg(bellaConnection)\n  File "/Library/Containers/.bella/Bella", line 1296, in recv_msg\n    return recvaux(sock, msglen, False)\n  File "/Library/Containers/.bella/Bella", line 1307, in recvaux\n    return pickle.loads(data) #convert from serialized into normal.\n  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1382, in loads\n    return Unpickler(file).load()\n  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 858, in load\n    dispatch[key](self)\n  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1151, in load_get\n    self.append(self.memo[self.readline()[:-1]])\nKeyError: \'et_client_inf\'\n\x1b[0m\n```\n'
p0
I01
tp1
.S'\x1b[31m[-] \x1b[0mMalfunction:\n```\n\x1b[31mTraceback (most recent call last):\n  File "/Library/Containers/.bella/Bella", line 1760, in bella\n    data = recv_msg(bellaConnection)\n  File "/Library/Containers/.bella/Bella", line 1296, in recv_msg\n    return recvaux(sock, msglen, False)\n  File "/Library/Containers/.bella/Bella", line 1307, in recvaux\n    return pickle.loads(data) #convert from serialized into normal.\n  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1382, in loads\n    return Unpickler(file).load()\n  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 858, in load\n    dispatch[key](self)\n  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1151, in load_get\n    self.append(self.memo[self.readline()[:-1]])\nKeyError: \'et_client_inf\'\n\x1b[0m\n```\n'
p0
I01
tp1
., THERE.IS.A.IP.HERE
               __________________________________________________________________

```

**Comment by xSynthx** [comment]
Also, can I suggest something to add, could you add a command that lets you take a picture through their camera? I would also suggest if you do add this, please make it to where the green light doesn't turn on when the picture is taken. I am almost 100% sure that root can do that.

**Comment by xSynthx** [comment]
Also, I went and got the 1 version posted about 12 days ago, as it does not have this error!

**Comment by xSynthx** [comment]
That version I think is a bit broken as, when I run a command *for example `pwd`* it gives a new line, but then I have to press enter again to get the output.

**Comment by manwhoami** [comment]
You did not update your Bella server. If you look at the commit history, you can see that this is necessary to use the new CC. Update your bella server with the new builder / payload [not just the Control Center]. 
```
p0
I01
tp1
``` 
is derived from an old data serialization protocol that bella no longer follows. 

Your issue with PWD should not happen if you update your bella server.

Also, it is not possible to turn off the light for the camera. There is extensive research on this.

I may add a function to take a picture [with the green light turning on] in the coming days.

**Comment by xSynthx** [comment]
Does this mean I have to get a new session on my target?

**Comment by xSynthx** [comment]
I mean, will I have to generate a new payload, and execute again?

**Comment by xSynthx** [comment]
I also think you mis understood,I ran this command to delete Bella folder: `rm -R Bella` if that clears that up :/

**Comment by manwhoami** [comment]
I think that is unlikely, given that the error you posted contains code that is only present on older versions of Bella.

Generate a new payload, and execute it on the target. Either do this physically, or remotely. To do it remotely using the Control Center, you have to use an older version of the Control Center, run the updateserver_yes command, and select the new payload you have generated. Then, close the connection, and use the new control center to connect to it. `rm -r Bella` does not mean much in this context.

**Comment by xSynthx** [comment]
okay, stay here

**Comment by xSynthx** [comment]
please wait

**Comment by xSynthx** [comment]
well, I deleted the old, and made an entirly new payload and executed it :/

**Comment by xSynthx** [comment]
but, when I did the `control` + `c` it still gave me all that error crap, and when I pressed `control` + `c` again, it let me type the connection, then it gave me the correct user bash line thing, and clear cleared it........

**Comment by manwhoami** [comment]
post the error here please.

**Comment by xSynthx** [comment]
well, my victim went offline, but, when I execute the payload on my mac, and I go back onto my VPS, it isnt detecting :/

**Comment by xSynthx** [comment]
he is back online

**Comment by xSynthx** [comment]
WELL, now it stopped doing the error, thanks for this issue!

**Comment by xSynthx** [comment]
Would you also mind updating the content of the `user_pass_phish` command please. I had the victim ask "But I am already connected to my network"

**Comment by manwhoami** [comment]
One of the beauties of open source is that you can look into the source code and learn how it works, and tweak it to your desire [what you suggest is not a bug fix, or an enhancement].

If you go to line 1720, you will see the subprocess call that invokes the dialog that appears when `user_pass_phish` is executed. You can change this call, including its text, as you desire.

If you want to change the colors, command text, etc, you can do all of that. It is all programmed within Bella, and it can all be changed as you see fit.
