### ISSUE TITLE
Exit error

### ISSUE THREAD

**Issue by xSynthx** [manwhoami/Bella#17]
When I exited bella after getting root on target, I got this error, I do not know if it is bad or not, but wanted to let you know!
```
Traceback (most recent call last):
  File "./Control Center.py", line 683, in <module>
    main()
  File "./Control Center.py", line 296, in main
    (data, isFinished) = recv_msg(connections[activate], False)
TypeError: 'NoneType' object is not iterable
```

**Comment by manwhoami** [comment]
Line 296 expects to receive a message over a socket. It gets None [hence the error], because the socket is closed, because Bella is reloading itself as root, as expected.

Please do not open issues like this, although I appreciate the thought.
