### ISSUE TITLE
set_client_name error

### ISSUE THREAD

**Issue by xSynthx** [manwhoami/Bella#18]
When I tried setting my client name, I got the following error *and yes, I am root*:
```
Traceback (most recent call last):
  File "/Library/Containers/.bella/Bella", line 1994, in bella
    name = data.split(":::")[1]
IndexError: list index out of range
```

**Comment by xSynthx** [comment]
and please make a discord server, it would be so benificial!

**Comment by manwhoami** [comment]
You are misusing the command. Type `set_client_name` and then press enter. You will see a dialog to enter the name. `set_client_name some_name` is the only way that that error could arise.

Again, please do not open issues that are not issues.
