### ISSUE TITLE
PLEASE make a discord server, I wont ask again tho :/

### ISSUE THREAD

**Issue by xSynthx** [manwhoami/Bella#19]
It would be so much better, as I would be able to talk with you about errors like this faster. I am asking nicely.

**Comment by xSynthx** [comment]
Or if you have discord, just lemme add you or something

**Comment by thehappydinoa** [comment]
Make one and I'll join

**Comment by manwhoami** [comment]
Guys, I will reiterate. Github and twitter only for issues. This is a public, open source project, and I will not be communicating over any private channels relating to it.

Reach out to me on twitter with future questions about how to use bella, or about how it works. If you have an actual bug report, or enhancement request, post it here.
