### ISSUE TITLE
Payload Generation

### ISSUE THREAD

**Issue by idekwhoIam** [manwhoami/Bella#22]
I recently updated Bella, and when I go to generate a new payload, and I run it on a client, the Control Center will detect it, BUT, it says malfunctioned :/ I dont know what is going on, and I cant get a old version of bella. I will update this post when I can recreate the error, because my client is offline right now. but I can `control` + `c` and it will ask me the enter number of client.... I enter the client number, and it does this:
```
Accepting Connection from [[-] Malfunction:
```
Traceback (most recent call last):
  File "/Users/THEUSER/Library/Containers/.bella/Bella", line 2116, in bella
    client_name = readDB('client_name')
  File "/Users/THEUSER/Library/Containers/.bella/Bella", line 144, in readDB
    c.execute("SELECT %s FROM bella WHERE id = %s" % (column, bella_UID))
OperationalError: no such column: client_name

```
] at [THEIR.IP.HERE]
Payloads requested. Sending payloads...
Injected payloads into Bella.
Last Connected:   File "/Users/THEUSER/Library/Containers/.bella/Bella", line 1898, in bella --     send_msg(initialize_socket(), True)
r```@[-] Malfunction:]-[Traceback (most recent call last):] clea

[```@[-] Malfunction:]-[Traceback (most recent call last):]                                    t
[```@[-] Malfunction:]-[Traceback (most recent call last):] exit
```
I even got the zip from the releases page, and when I finish trying to build bella.py, I get this error, even when I run as root.
```
What should the Launch Agent named? Default is [com.apple.Bella]: main.apple.loader
Where should Bella be stored in ~/Library/? Default is [Containers/.bella]:
Where should Bella connect to: MY.IP.HERE
What port should Bella connect on [Default is 4545]:
Configuring your Bella installation
sed: can't read : No such file or directory
sed: can't read : No such file or directory
sed: can't read : No such file or directory
sed: can't read : No such file or directory
sed: can't read : No such file or directory
sed: can't read : No such file or directory
Error inserting config variables!
```

**Comment by manwhoami** [comment]
I have added error handling for the sqlite `no such column` issue.

The release with the `sed...` error, is an older release that doesn't have support for Linux. I have updated the releases page.

Thanks for report.

**Comment by idekwhoIam** [comment]
When I update the Control Center, and Bella.py, will I have to make a new payload and run it on the victim?

**Comment by manwhoami** [comment]
Yes. You can run it on the target by running updateserver_yes. If this fails, you will have to do it physically.

**Comment by idekwhoIam** [comment]
Good thing I have 2 other backdoors

**Comment by idekwhoIam** [comment]
btw, I am xsynthx *Synthx*, will you please let my real account post, and make issues, I am sorry for what I did, and it wont happen again.
