### ISSUE TITLE
get remote Bella.py version

### ISSUE THREAD

**Issue by Skeyelab** [manwhoami/Bella#23]
is there a way to ensure our versions are up to date?

If you include a version # in CC and Bella.py, we could coordinate them somehow.

Thoughts?

**Comment by manwhoami** [comment]
Great idea! Don't know why I left this out to begin with. Just pushed this update. `bella_version` will print the version of the remote bella server, and the control center. 

This should help determine what your remote instance is running on. 

I may add this to the initial information that is printed about bella [that is, `Last Connected: ...` etc] 

I do not want to make the CC drown in text, so for now, you can just run bella_version.
