### ISSUE TITLE
I would love a possibility to Open a "view only" VNC Connection. 

### ISSUE THREAD

**Issue by ochsenjoch** [manwhoami/Bella#27]
It would be nice if i could switch my interaction on or off, so that i don't interfere with the system if i don't intend to.

**Comment by manwhoami** [comment]
You can do this within the VNC Viewer App. Preferences -> View only. Let me know if this does what you need!

**Comment by ochsenjoch** [comment]
yes, it does. i'm sorry, i should have found that myself... kind of strange that it doesnt show in the menu bar i'm so used to use the shortcut as well.

Thank you very much.
