### ISSUE TITLE
Target is online but wont connect to me back.

### ISSUE THREAD

**Issue by mineo210** [manwhoami/Bella#29]
I got a root shell before of this target with bell but suddenly it stopped working.
I think it was when I played around with VNC and then the connection just cut off.. tho it said on Eggshell that he was still online (getting connection with bash)

**Comment by manwhoami** [comment]
If Bella crashes for some reason, it sends a log back to the control center with a traceback. Please post that here.

**Comment by mineo210** [comment]
alright, got it fixed!
