### ISSUE TITLE
Enhancement: get_root in a manual fashion

### ISSUE THREAD

**Issue by BlackDeveraux** [manwhoami/Bella#32]
Hello!

I've been losing clients here and there, but I've learnt to use a DNS to keep them hooked, this helps when the local DHCP servers randomly assign IP addresses.

I was wondering if it would possible for you to implement a small feature in which we manually enter the password (if we know it already) and have Bella attempt to gain root access, and throwing an error if it's incorrect.

I'm suggesting this because I run into scenarios when the standard `user_pass_phish` dialog becomes cliches for certain clients.

Cheers!

**Comment by mineo210** [comment]
I hope this gets implemented !

What DNS service are you using?

**Comment by BlackDeveraux** [comment]
@mineo210 
I purchased a Secure DNS solution from a guy I'm familiar with. But prior to setting up a custom DNS solution, I went with No-IP. 

In addition to No-IP, there's DuckDNS etc. but I don't suggest using these services because they tend to have honeypots setup if you're not using them for educational purposes.

**Comment by mineo210** [comment]
@BlackDeveraux Thanks!

**Comment by manwhoami** [comment]
Nice idea. I will add this feature in the next update, along with manual entering of iCloud passwords, chrome and iCloud tokens. Thanks for suggestion!

**Comment by RogueRuins** [comment]
Hey also one other thing, this is the most recent privilege escalation tool rn https://github.com/zhengmin1989/macOS-10.12.2-Exp-via-mach_voucher it is for macOS 10.12.2 and it works quite nicely, maybe you could add to get_root

**Comment by BlackDeveraux** [comment]
@RogueRuins

That looks very cool! Thanks for sharing :)

**Comment by RogueRuins** [comment]
Ya ofc man

**Comment by manwhoami** [comment]
@RogueRuins I was checking this out yesterday actually. I haven't been able to get it to work on a 10.12.2 machine, but I will keep trying.

**Comment by RogueRuins** [comment]
Oh, huh hope you can find a way
