### ISSUE TITLE
"b" key is not working. Any solutions or recommendations for those who has it working?

### ISSUE THREAD

**Issue by mineo210** [manwhoami/Bella#33]
pretty what the title says, I hope this gets fixed since it's pretty annoying :/

thanks!

**Comment by Scriptkidy** [comment]
B Key Works for me
Check `Sticky Keys` in System Preferences
Turn it off if its on

**Comment by mineo210** [comment]
@Scriptkidy thanks! I'll try that!

**Comment by mineo210** [comment]
@Scriptkidy was already off :(

**Comment by RogueRuins** [comment]
Oh rip

**Comment by manwhoami** [comment]
Please post information about your control center system.

That is, OS Version, and any python packages installed related to readline.

**Comment by mineo210** [comment]
@manwhoami os version is 10.12.1 but how do I know what python packages i installed that uses the module readline ??

**Comment by manwhoami** [comment]
No need for that information actually. I just updated the control center to remove the need for gnureadline, and added a special tab parser if there is a macOS vs linux system. Update your control center, and your issue should be resolved.

**Comment by mineo210** [comment]
@RogueRuins Thanks!
