### ISSUE TITLE
LPE not working on 10.11.3

### ISSUE THREAD

**Issue by ochsenjoch** [manwhoami/Bella#34]
i have a machine where i am testing the get_root function.

It is running 10.11.3 but the command returns the following error(s):

 get_root
[*] We are not root. Attempting to root.
[-] No user password found. Run 'phish_user_pass' to phish this. It should give us root.
unzip /var/folders/vj/vsy9knz53xv51flfbcyxb3s00000gn/T/tmpnV6x0J/americangirl -d /var/folders/vj/vsy9knz53xv51flfbcyxb3s00000gn/T/tmpnV6x0J/

[*] User is susceptible to LPE!
[+] SUID root file written to /var/folders/vj/vsy9knz53xv51flfbcyxb3s00000gn/T/roots!
[-] Error creating path:
	mkdir: /Library/Containers/.bella/: Permission denied

Than i'm back to shell...

**Comment by manwhoami** [comment]
It is possible that the computer has a security patch installed, although this is unlikely..

If you check About this mac -> system report -> software -> security update

What do you see?

**Comment by ochsenjoch** [comment]
the only relevant updates that have been installed are 10.11.3 combo update and osx recovery update, so no security patches. I have also tried installing the newest version of the bella payload, same result

**Comment by manwhoami** [comment]
I have updated Bella to handle < 10.12.2 for LPE. Let me know how this works for you.
