### ISSUE TITLE
JavaScript payload or features??

### ISSUE THREAD

**Issue by mineo210** [manwhoami/Bella#36]
So I saw a "rat" that works on MacOS but is in beta that uses java.. has some good features.
just wondering is this possible if you somehow implemented some java code inside of the python payload.. since java is also pre-installed onto os x. just wondering :)

rat name is "SilentBytes" and it's not for free, still in beta so far..

**Comment by manwhoami** [comment]
I have no intention of doing this. And the default version of java is an older version if i recall correctly. Feel free to submit some of the features that it has as feature requests.
