### ISSUE TITLE
Connecting to victim isn't working!

### ISSUE THREAD

**Issue by mineo210** [manwhoami/Bella#38]
I get his:
Payloads requested. Sending payloads...
Error injecting payloads Payloads requested. Sending payloads...

**Comment by mineo210** [comment]
and I get this:
Payloads requested. Sending payloads...
Error injecting payloads
Traceback (most recent call last):
  File "Control Center.py", line 683, in <module>
    main()
  File "Control Center.py", line 298, in main
    string_log(data, client_log_path, client_name)
  File "Control Center.py", line 53, in string_log
    with open(os.path.join(client_log_path, client_name + ".txt"), "ab") as content:
IOError: [Errno 13] Permission denied: '.txt'

**Comment by Scriptkidy** [comment]
I don't know 🤔 maybe try to open control center with 'sudo python Control\ Center'
Maybe that will work 😐.

**Comment by mineo210** [comment]
then I get the this:
Payloads requested. Sending payloads...
Error injecting payloads Payloads requested. Sending payloads...
Error injecting payloads Payloads requested. Sending payloads...
Error injecting payloads Payloads requested. Sending payloads...
Error injecting payloads Payloads requested. Sending payloads...

**Comment by manwhoami** [comment]
Make sure you are running the Control Center from the same directory that it is locating in. I.E. , cd 

/Users/Name/Desktop/Bella-Master/

and then run 'python Control\ Center.py'
