### ISSUE TITLE
mitm_start doesn't work for me.

### ISSUE THREAD

**Issue by mineo210** [manwhoami/Bella#40]
I get this when  I run it:
🚀  Specify an interface to MITM [Press enter for Wi-Fi]: 
[-] Error injecting root CA into System Keychain:
[*] We are root, but there was an error.
[*] SecCertificateAddToKeychain: UNIX[Operation not permitted]

tho it have worked before on the same victim with the same ".pem" file

**Comment by manwhoami** [comment]
Sorry about that, I just pushed changes to fix this. I changed some code in a recent update that causes this issue.

I changed the keychain that it adds itself to, and I also added a feature to regenerate a certificate if you so desire (would not cause any issues if you didn't however).

Thanks for this!
