### ISSUE TITLE
Use a dns in host

### ISSUE THREAD

**Issue by ShellBear** [manwhoami/Bella#46]
Hello, just a question i tried to use in host my DNS from no-ip but its not working, i don't receive any connection. Here an example of what DNS looks like : *********.ddns.net
I don't know how to use it because due to my dynamic ip, my ip (so the host) change every week.

Thank you

**Comment by manwhoami** [comment]
This is unlikely due to an issue in Bella. The DNS is definitely pointing to your control center? And are all ports appropriately forwarded on your CC's router?

**Comment by BlackDeveraux** [comment]
I have a custom DNS solution set up for Bella. As long as you maintain the
correct IP configured for your DNS, and that your ports are correctly port
forwarded (which you can test using services such as canyouseeme.org) it'll
work out perfectly fine.

**Comment by ShellBear** [comment]
Do someone success using no-ip ? Because I'm not able to make it works with bella. Or maybe is it possible to change commandt by resolving it instead of connect directly to hostname ?
In bash it would be something like this : dig +short hostname.ddns.net
Don't know if its possible to resolve domain everytime before connect to it in python, in order to modify bella and makes it works

**Comment by manwhoami** [comment]
The socket function resolves all DNS, so that would not be the issue. If you run the Control Center, and go to `canyouseeme.org` and enter the Control Center's port, do you see anything? If you do not, it is an issue with port forwarding.

**Comment by Scriptkidy** [comment]
I use no-ip and it works try updating your no-ip host ip ;)
