### ISSUE TITLE
Special characters in user password

### ISSUE THREAD

**Issue by ABorrello** [manwhoami/Bella#47]
I was performing a pen test the other day, and I managed to extract the password for one of the users on a machine that I have Bella running on.
The problem was that the users password was literally a single special character (in this case it was the apostrophe character `'` )

When I tried to update the database using `update_db_entry`, I constantly received an error saying:
```
/bin/sh: -c: line 0: unexpected EOF while looking for matching `''
/bin/sh: -c: line 1: syntax error: unexpected end of file
```

When I tried to escape the character, I received this error:
```
/bin/sh: update_db_entry:::localPass:::user:': command not found
```

Sorry if this is a duplicate question, but I could not find any information after a looking through previous issues.
Also, I was wondering how it would handle other special characters in passwords such as a backward slash `\` or a semicolon `;` ?

**Comment by manwhoami** [comment]
Thanks for reporting. I will fix this.

**Comment by manwhoami** [comment]
Thanks for the detailed report! I am unable to reproduce this on the latest version of Bella. Here is what I tried:
`Entered command: update_db_entry`
`Selected [2]: User Password`
`Entered username: my_user`
`Entered password: '`

I also tried with a back slash and semicolon and got no error.

It seems as if your remote Bella instance is not recognizing the preprogrammed command `update_db_entry`, so it interprets it as a bash command, and that is why you get the bash error you see.

The `update_db_entry` feature was added [on March 10, 2017](https://github.com/manwhoami/Bella/commit/9fc9a8ea041a8a5d7aee5be4b60a19e42d32d77d)

You likely updated your control center, but not your remote Bella instance. You should reinstall the server, and give it a go.

**Comment by ABorrello** [comment]
Thanks for the help, you were right, the version was out of date.
