### ISSUE TITLE
iOS_sms

### ISSUE THREAD

**Issue by iownbish** [manwhoami/Bella#48]
Last Connected: Sat, Apr 15 2017 at 08:53:02 AM -- 49:20
[uh@MacBook-Pro]-[~] iOS_sms
[*] Found the following SMS files:
	
[*] Processing...
[*] Sending data over.

Traceback (most recent call last):
  File "Control Center.py", line 768, in <module>
    main()
  File "Control Center.py", line 410, in main
    (name, data, backup_name) = x.split('FFA82F16')
ValueError: need more than 1 value to unpack

**Comment by iownbish** [comment]
?

**Comment by manwhoami** [comment]
Thanks for reporting, I will look into this.

**Comment by manwhoami** [comment]
Fixed in the latest update. Thanks for report!

**Comment by iownbish** [comment]
Accepting Connection from [keefy] at [96.19.148.239]
Last Connected: Sat, Apr 15 2017 at 05:30:33 PM -- 24:02
[uh@keefy]-[/private/var/root] iOS_sms
[*] Found the following SMS files:
	
[*] Processing...
[*] Sending data over.

Traceback (most recent call last):
  File "Control Center.py", line 777, in <module>
    main()
  File "Control Center.py", line 410, in main
    (name, data, backup_name) = x.split('FFA82F16')
ValueError: need more than 1 value to unpack
uh @ Bella $ git pull
Already up-to-date.
uh @ Bella $ 


still not working, after i've updated
