### ISSUE TITLE
Error building 

### ISSUE THREAD

**Issue by drtaru** [manwhoami/Bella#5]
when building bella I get the following error.

`Configuring your Bella installation`
`sed: 1: "Builds/02-13@13_02/bell ...": invalid command code B`
`sed: 1: "Builds/02-13@13_02/bell ...": invalid command code B`
`sed: 1: "Builds/02-13@13_02/bell ...": invalid command code B`
`sed: 1: "Builds/02-13@13_02/bell ...": invalid command code B`
`sed: 1: "Builds/02-13@13_02/bell ...": invalid command code B`
`sed: 1: "Builds/02-13@13_02/bell ...": invalid command code B`
`Error inserting config variables!`

**Comment by manwhoami** [comment]
Had a typo in the last commit. Please re-download
