### ISSUE TITLE
iOS_sms error still persisting

### ISSUE THREAD

**Issue by iownbish** [manwhoami/Bella#50]
Accepting Connection from [keefy] at [96.19.148.239]
Last Connected: Sat, Apr 15 2017 at 05:30:33 PM -- 24:02
[uh@keefy]-[/private/var/root] iOS_sms
[*] Found the following SMS files:

[] Processing...
[] Sending data over.

Traceback (most recent call last):
File "Control Center.py", line 777, in 
main()
File "Control Center.py", line 410, in main
(name, data, backup_name) = x.split('FFA82F16')
ValueError: need more than 1 value to unpack
uh @ Bella $ git pull
Already up-to-date.
uh @ Bella $

still not working, after i've updated

**Comment by manwhoami** [comment]
You have to update your remote Bella install with a newly built payload

**Comment by manwhoami** [comment]
Did you try the above, and if so, was the issue resolved?

**Comment by manwhoami** [comment]
Closing to lack of response. Fairly certain patch resolved issue.
