### ISSUE TITLE
How to find if my mac is infected ;) and How can I remove it ?

### ISSUE THREAD

**Issue by johnnash999** [manwhoami/Bella#51]
I actually infected myself for testing ;) want to remove it now :D

**Comment by manwhoami** [comment]
Can you connect to it from the control center? If so, run the `remove_server` command.

If not, then the default install path for Bella is the following:

`~/Library/Containers/.Bella`. Remove this folder, and remove `~/Library/LaunchAgents/com.apple.Bella.plist`. Then run `launchctl remove com.apple.Bella` 

and you'll be all clear.
