### ISSUE TITLE
Can i use domain instead of IP address in Host ?

### ISSUE THREAD

**Issue by johnnash999** [manwhoami/Bella#52]
I actually tried and it seems not to be working fine.

I tried `host `in this format ->  sub.mymainsite.com  

// no http:// and all. just the domain name

**Comment by manwhoami** [comment]
There have been some other reported issues of this. As far as I can tell, it is not a Bella related issue. 

See the comments here

[Issue 46 - reference](https://github.com/manwhoami/Bella/issues/46)
