### ISSUE TITLE
VNC - "There is not yet Linux support" Error

### ISSUE THREAD

**Issue by johnnash999** [manwhoami/Bella#53]
MacBook-Air]-[~]  vnc
[-] There is not yet Linux support for a reverse VNC connection.

But it is my personal mac. and i have VNC installed in my MAC too.

**Comment by manwhoami** [comment]
Quite strange. If you open a python console and enter the following:

`import platform`
`platform.system()`

What do you see?

**Comment by johnnash999** [comment]
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.system()
'Darwin'
>>> 

I see this in my local mac, in python console.

**Comment by manwhoami** [comment]
The error you are seeing is only printed when the following code is evaluated to true:

`if platform.system() == 'Linux'`

So I am not sure why you are seeing this issue, especially since it evaluates to Darwin in a normal shell.

**Comment by johnnash999** [comment]
oh! wait. i have the server installed in a ubuntu server :v is that why it is giving me that error ? :D

and i ran that in my mac, which is the victim ?

**Comment by manwhoami** [comment]
So your Control Center is running on Ubuntu, and the actual payload is running on a mac.

Yes, this is expected. VNC support coming soon! (just have to integrate with Bella's automation functions)
