### ISSUE TITLE
How to setup the port for other computers? 

### ISSUE THREAD

**Issue by kolya009** [manwhoami/Bella#55]
So when setting up Bella, It asks for an ip address, what ip am I supposed to use? Then when running the control center.py, it says it's looking for other devices on the port "4545". How am I supposed to get other computers on that port? Maybe I'm over thinking this but I'm just really having a hard time.

**Comment by manwhoami** [comment]
The IP address should be the IP of the computer that is running the Control Center, and port 4545 is the default port that Bella runs on. They will be sending out connections on that port as soon as you run the Bella payload on them, and the Control Center will be listening for these connections.

Does this help?

**Comment by kolya009** [comment]
I think it just might. I can try it in the morning and test it.
I'll update you later on
