### ISSUE TITLE
how to delete bella completely 

### ISSUE THREAD

**Issue by kolya009** [manwhoami/Bella#57]
How would I remove all traces of Bella from my mac? Does it also keep a log that I gained root access? Also, is there any indication that Bella was used in the Console.app?

**Comment by manwhoami** [comment]
Bella has a few anti-forensic functions built in, but nothing crazy advanced. If you gained root access via password phishing, there will be a log for this that Bella does not delete (but at first glance [and without referring to other logs to cross reference the time of login etc] this should be indistinguishable from say a normal login). If you gained root access via local privilege escalation, there are no logs left behind.

Depending on the functions you used, different logs would be written to different places. When you call the `removeserver_yes` function, it removes any trace of Bella itself, but there could be logs left behind of actions that Bella invokes, as mentioned above. 

Also, depending on any files you uploaded, there may be traces of those files that remain long after you delete them (if you delete them through a conventional delete, not a secure delete), and there is nothing you can do about removing this.
