### ISSUE TITLE
Cannot run control center.py

### ISSUE THREAD

**Issue by KILLBULL** [manwhoami/Bella#59]
When I try to open control center I get this error n. 2

>Mario$ python control center.py
/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'control': [Errno 2] No such file or directory

I tried also to run it with python launcher but with no success.
May I get any support?

**Comment by ABorrello** [comment]
It looks like you are not escaping the space in the `Control Center.py` file name. As a result, python is looking for a file named `control` and it is passing `center.py` as an argument to said file.
To fix this, simply escape the space with the backward slash character (`\`).
Your command should look something along the lines of this `python Control\ Center.py`
Hope this helps!

**Comment by KILLBULL** [comment]
This definitely helped!
Issue due to my inexperience. Thank you very much for you answer.
