### ISSUE TITLE
Losing Clients after Reboot

### ISSUE THREAD

**Issue by BlackDeveraux** [manwhoami/Bella#6]
Greetings,

I've been able to gain root access on a number of computers I'm testing Bella on. However, even with root privileges, I lose my clients after they reboot their machine.

Any thoughts?

**Comment by manwhoami** [comment]
Hmm, peculiar. Two possibilities:
1.) The LaunchDaemon isn't loading for some reason.
2.) The LaunchDaemon is loading, but Bella is not connecting to the CC.

On the clients, can you run `ps aux | grep python` in a terminal and post the output here? Also, run `launchctl list | grep Bella` and post that output.

**Comment by BlackDeveraux** [comment]
I had 3 clients earlier with root access, and two of them are now lost (just thought I'd share).
Here are the results on the remaining client:
<img width="870" alt="screen shot 2017-02-14 at 11 30 00 am" src="https://cloud.githubusercontent.com/assets/7029790/22913980/0c984e2e-f2a9-11e6-8660-fd2d8b660995.png">

**Comment by manwhoami** [comment]
Okay, so all is good with the Launch Daemons. Bella itself is running. If you'd be interested in helping debug, that'd be great.

After this line on the top of Bella, ```<key>StartInterval</key>
<integer>5</integer>``` can you add this line. It will help debug.

```
<key>StandardErrorPath</key>
<string>/private/var/root/stderr.log</string>
<key>StandardOutPath</key>
<string>/private/var/root/stdout.log</string>
```

Then in BUILDER, comment out these two lines 

```sed -i "s@\(^[[:space:]]*\)\(print.*$\)@@g" $BuildsPath/bella.py```
```sed -i '' -e "s@\(^[[:space:]]*\)\(print.*$\)@@g" $BuildsPath/bella.py```

What all of this will do, is essentially make a clear, timed log of what is happening and what goes wrong after the reboot. 

Run BUILDER after you make the edits

You will have to run `removeserver_yes` on the faulty machines, and then reinstall Bella with the new Build.

Reboot, see if you have the same issue (you should). Then, post the logs that will be written to `/private/var/root`.

Thanks a ton.

**Comment by BlackDeveraux** [comment]
I'd love to, I'll get back to you soon.

**Comment by manwhoami** [comment]
Oh, quick update. I realize that you posted results for the remaining client. To see what is going on, you need to post results for the clients that you lost (this would require physically going to the machines and running the `ps aux...` , etc, commands.

**Comment by BlackDeveraux** [comment]
Haha, you had me wondering :)
I'll let you know when I'm able to run the diagnostics.

**Comment by manwhoami** [comment]
Closing to inactivity. 

To debug, change the line `development=false` to `development=true` in BUILDER. Rebuild, redistribute, post logs in Bella's folder
