### ISSUE TITLE
Bella not connecting to CC

### ISSUE THREAD

**Issue by skyberry333** [manwhoami/Bella#9]
Hi, thank you for everything!
I had a little issue setting up Bella, not sure if I misunderstood the "How to use" part. For the most parts i just used the default setting except for Command and control, I put my IP address and run the build on another laptop in the same network. During the process there's no error occurred but I didn't see my another laptop popping up in the control center. 
I'm not sure what went wrong, so just kinda asking what should I do to set it up correctly.

**Comment by manwhoami** [comment]
Reposting advice from [Issue #6]

----- Begin Repost -----

Hmm, peculiar. I do not have this issue. Two possibilities:
1.) The LaunchDaemon isn't loading for some reason.
2.) The LaunchDaemon is loading, but Bella is not connecting to the CC.

On the clients, can you run `ps aux | grep python` in a terminal and post the output here? Also, run `launchctl list | grep Bella` and post that output.

**Comment by skyberry333** [comment]
@manwhoami This is the output.

```
LAPAC-20:~ skyberry$ ps aux | grep python
skyberry           526   0.0  0.0  2477576   2016   ??  S    Mon03PM   0:10.27 python /Users/skyberry/Library/Containers/.bella/Bella
skyberry          4526   0.0  0.0  2423400    404 s000  R+   10:31PM   0:00.00 grep python
LAPAC-20:~ skyberry$ launchctl list | grep Bella
526	0	com.apple.Bella
```

I looked up my ip by using `curl ifconfig.me` which should be correct.

**Comment by manwhoami** [comment]
It is possible a blocking process was opened. Try running `killall -9 python` on the Bella machine (through a non-bella connection), and seeing if it will connect then. If it does, then a blocking process was opened. If it doesn't, something else is going on.

**Comment by thehappydinoa** [comment]
Hey, I am also having a similar issue, I tried to install Bella on a iMac running 10.11.4, it launches and deletes itself but it will not connect to CC. I have it running on about 10 Mac Book Airs running macOS 10.11.6. Hope you figure it out, thanks!

**Comment by manwhoami** [comment]
I am looking into this issue. I will also be adding a debugging module to Bella so that easy bug reports can be generated.

**Comment by manwhoami** [comment]
@thehappydinoa I have updated Bella with a debugging module. If you re download Bella, and in the builder, change the line at the top that says 'development=true', to 'development=false', and then build bella, and install on the iMac running 10.11.4, it should give you some information about what is going on. 

Two log files will be placed in your Bella installation folder. Can you upload those after you do this? If you are still willing to try this of course. 

Thanks

**Comment by JPaulMora** [comment]
Don't know if its related, but sometimes bella (or python socket) hangs.. and since python is still running launchctl doesnt restart it. I know it would be hard to check where or when does it hang, so why not add a timeout for bella to quit (and relaunch via Launch Daemons)?

**Comment by manwhoami** [comment]
I believe that the last update or two to Bella should have resolved any blocking / hanging pipes. That being said, there are some very rare situations that *could* arise that would block the pipe. This is a tricky task. Try updating and let me know if it still hangs. I will look into launchctl methods for periodically flushing the server.

**Comment by JPaulMora** [comment]
OK, I updated and bella seems to hang when ^C chrome_dump function.

**Comment by manwhoami** [comment]
That is unlikely a blocking pipe, and is more likely related to the Control Center being confused as to what is going on. Please see the latest update, it may or may not fix your issue. It brings better CTRL-C usage, better error handling, and WAY faster data transport. See the note about updating old clients too.

**Comment by JPaulMora** [comment]
Thanks, will update ASAP. I tested this chrome_dump error a little more, and it seems that when the server looses connection mid-function, it doesn't connect back.

**Comment by manwhoami** [comment]
@JPaulMora can you post the exception it sends where it is crashing? There are no blocking calls in the chrome_dump function.
